### ISSUE TITLE
About data

### ISSUE THREAD

**Issue by SongFGH** [PetarV-/GAT#13]
Hi, I know the GAT model can apply to node classification. And in your paper, the node classification is executed in transductive learning.
However, why your data is ind.cora.xxx? This data is used in inductive learning!

**Comment by PetarV-** [comment]
Hello,

If you observe how the data is constructed:
https://github.com/PetarV-/GAT/blob/master/utils/process.py#L45-L96
all features end up being visible to the training algorithm, so it is a transductive setup. The inductive details are there solely in order to compute the necessary label masks.

It is, in fact, constructed identically as in Thomas Kipf's GCN repository.

Thanks,
Petar
